export default function inGameMessage() {
  const arrLastIdex = 69;
  return sentences[Math.floor(Math.random() * arrLastIdex)];
}

const sentences = [
  "Perfect! That's the card!",
  "Yes! The puzzle fits!",
  "This card seals it!",
  "Right card — fate approved.",
  "Got it! Victory's closer.",
  "Bingo. Game on!",
  "That's the one I was waiting for.",
  "Exactly what I needed!",
  "The duel turns in our favor.",
  "Piece by piece, we win.",
  "Right card, right time.",
  "That's destiny showing up.",
  "Full speed ahead!",
  "The odds just shifted.",
  "Luck’s on our side now.",
  "That card changes everything.",
  "Now we're cooking!",
  "Hold tight — it's working.",
  "One step closer to victory.",
  "Yes — that seals the plan.",
  "The duel answers us.",
  "A perfect play revealed.",
  "That's our trump card.",
  "We found our edge!",
  "This is the move.",
  "All systems go.",
  "Flawless pick.",
  "The tide turns.",
  "Right card, right move.",
  "We strike now!",
  "The combo is alive!",
  "That charge ignites hope.",
  "That's how we do it.",
  "A key piece unlocked.",
  "The path clears.",
  "Victory feels near.",
  "This is the breakthrough.",
  "Our strategy clicks.",
  "Onward — let's finish this.",
  "That's the spark we needed.",
  "Perfect timing.",
  "This card speaks destiny.",
  "Now it's our moment.",
  "Everything's aligning.",
  "The answer was here all along.",
  "We play with confidence.",
  "Now watch this.",
  "That's a game changer.",
  "Piece set. Move made.",
  "This will tip the scales.",
  "Ready to win.",
  "The stars favor us.",
  "That’s the final touch.",
  "We’ve got momentum.",
  "No turning back now.",
  "Feel that? It's our chance.",
  "Precision pick.",
  "On target — execute!",
  "That's the key move.",
  "We keep pushing forward.",
  "A decisive card.",
  "Our hearts led us here.",
  "We draw power from hope.",
  "One card, many possibilities.",
  "We rise with this play.",
  "That's the cue — play it.",
  "Hope fuels the duel.",
  "Aim true — victory awaits.",
  "This is the moment.",
  "Now let's win it!"
];