export default function inGameMessage() {
  const arrLastIdex = 69;
  return sentences[Math.floor(Math.random() * arrLastIdex)];
}

const sentences = [
  "Yugi: Perfect! That's the card!",
  "Yugi: Yes! The puzzle fits!",
  "Yugi: This card seals it!",
  "Yugi: Right card — fate approved.",
  "Yugi: Got it! Victory's closer.",
  "Yugi: Bingo. Game on!",
  "Yugi: That's the one I was waiting for.",
  "Yugi: Exactly what I needed!",
  "Yugi: The duel turns in our favor.",
  "Yugi: Piece by piece, we win.",
  "Yugi: Right card, right time.",
  "Yugi: That's destiny showing up.",
  "Yugi: Full speed ahead!",
  "Yugi: The odds just shifted.",
  "Yugi: Luck’s on our side now.",
  "Yugi: That card changes everything.",
  "Yugi: Now we're cooking!",
  "Yugi: Hold tight — it's working.",
  "Yugi: One step closer to victory.",
  "Yugi: Yes — that seals the plan.",
  "Yugi: The duel answers us.",
  "Yugi: A perfect play revealed.",
  "Yugi: That's our trump card.",
  "Yugi: We found our edge!",
  "Yugi: This is the move.",
  "Yugi: All systems go.",
  "Yugi: Flawless pick.",
  "Yugi: The tide turns.",
  "Yugi: Right card, right move.",
  "Yugi: We strike now!",
  "Yugi: The combo is alive!",
  "Yugi: That charge ignites hope.",
  "Yugi: That's how we do it.",
  "Yugi: A key piece unlocked.",
  "Yugi: The path clears.",
  "Yugi: Victory feels near.",
  "Yugi: This is the breakthrough.",
  "Yugi: Our strategy clicks.",
  "Yugi: Onward — let's finish this.",
  "Yugi: That's the spark we needed.",
  "Yugi: Perfect timing.",
  "Yugi: This card speaks destiny.",
  "Yugi: Now it's our moment.",
  "Yugi: Everything's aligning.",
  "Yugi: The answer was here all along.",
  "Yugi: We play with confidence.",
  "Yugi: Now watch this.",
  "Yugi: That's a game changer.",
  "Yugi: Piece set. Move made.",
  "Yugi: This will tip the scales.",
  "Yugi: Ready to win.",
  "Yugi: The stars favor us.",
  "Yugi: That’s the final touch.",
  "Yugi: We’ve got momentum.",
  "Yugi: No turning back now.",
  "Yugi: Feel that? It's our chance.",
  "Yugi: Precision pick.",
  "Yugi: On target — execute!",
  "Yugi: That's the key move.",
  "Yugi: We keep pushing forward.",
  "Yugi: A decisive card.",
  "Yugi: Our hearts led us here.",
  "Yugi: We draw power from hope.",
  "Yugi: One card, many possibilities.",
  "Yugi: We rise with this play.",
  "Yugi: That's the cue — play it.",
  "Yugi: Hope fuels the duel.",
  "Yugi: Aim true — victory awaits.",
  "Yugi: This is the moment.",
  "Yugi: Now let's win it!"
];