export default function lostMessage() {
  const arrLastIndex = 49;
  return gameOverLines[Math.floor(Math.random() * arrLastIndex)]; 
}

const gameOverLines = [
  "Yugi: No... I'm trapped by the ring.",
  "Yugi: The Orichalcos holds me fast.",
  "Yugi: Your duel ends here...",
  "Yugi: Darkness sealed my spirit.",
  "Yugi: I can feel the chain tight.",
  "Yugi: This can't be the final move...",
  "Yugi: My heart... it's fading.",
  "Yugi: I'm lost within its shadow.",
  "Yugi: The ring claimed me... forgive me.",
  "Yugi: My spirit won't break free now.",
  "Yugi: I knew this risk... but—",
  "Yugi: Promise me you'll continue.",
  "Yugi: I can't reach you from here.",
  "Yugi: The Orichalcos laughs at us.",
  "Yugi: I'm trapped, but not forgotten.",
  "Yugi: The duel falls into darkness.",
  "Yugi: My light dims as you falter.",
  "Yugi: I believed in you... still do.",
  "Yugi: This loss binds me tightly.",
  "Yugi: Don't let my trap be in vain.",
  "Yugi: My voice grows faint...",
  "Yugi: I am sealed inside the ring.",
  "Yugi: The shadows consume my words.",
  "Yugi: Even here, I feel your courage.",
  "Yugi: You fought well... I'm sorry.",
  "Yugi: The Orichalcos has its prize.",
  "Yugi: I draw my last breath here.",
  "Yugi: Your heart slips from my reach.",
  "Yugi: This defeat silences me now.",
  "Yugi: I'm captured—keep fighting on.",
  "Yugi: My chains are cold and strong.",
  "Yugi: The duel's light has been snuffed.",
  "Yugi: I believed we'd break it.",
  "Yugi: My spirit sinks into shadow.",
  "Yugi: Hold onto our memories, friend.",
  "Yugi: I can barely feel the world.",
  "Yugi: The ring's grip grows tighter.",
  "Yugi: Your choice sealed our fate.",
  "Yugi: Fear not for me—stand tall.",
  "Yugi: I wish I could guide you now.",
  "Yugi: My duel ends, but yours continues.",
  "Yugi: The Orichalcos claimed my smile.",
  "Yugi: I'll wait for you, somewhere.",
  "Yugi: The silence answers where I am.",
  "Yugi: My cards fall silent around me.",
  "Yugi: Even trapped, I believe in you.",
  "Yugi: This pain is real... carry on.",
  "Yugi: I hoped for better outcomes.",
  "Yugi: Remember our bond—fight on.",
  "Yugi: Farewell for now... be brave."
];
