export default function openingMessage() {
  const arrLastIndex = 49;
  return openingSentence[Math.floor(Math.random() * arrLastIndex)];
}

const openingSentence = [
  "Yugi: Trust your Duel Spirit, free me!",
  "Yugi: I believe in you—break the ring!",
  "Yugi: Your courage can shatter Orichalcos.",
  "Yugi: Don't give up—free my spirit!",
  "Yugi: One duel at a time, victory comes.",
  "Yugi: Your heart will find the key.",
  "Yugi: Stay focused, the ring will weaken.",
  "Yugi: I feel your strength—push on!",
  "Yugi: Every move brings me closer.",
  "Yugi: Use your wit, break the darkness.",
  "Yugi: Courage and heart will win this.",
  "Yugi: Light your spirit against the ring.",
  "Yugi: You are the key—claim it now.",
  "Yugi: Keep fighting, I can feel hope.",
  "Yugi: Let your bonds guide the duel.",
  "Yugi: I trust you—strike true!",
  "Yugi: Believe, then act with heart.",
  "Yugi: The Orichalcos trembles—hold firm.",
  "Yugi: One brave play can change fate.",
  "Yugi: Don't be afraid to take risks.",
  "Yugi: Your resolve is my rescue.",
  "Yugi: Show them the strength of heart.",
  "Yugi: Keep your faith—break its hold.",
  "Yugi: Your hands can free us both.",
  "Yugi: Stand tall, the duel favors you.",
  "Yugi: Focus now; destiny awaits.",
  "Yugi: Each card is hope—play it well.",
  "Yugi: I draw courage from you.",
  "Yugi: Let passion guide your strategy.",
  "Yugi: Trust your instincts, they're true.",
  "Yugi: I feel light when you fight on.",
  "Yugi: Push past fear—claim victory.",
  "Yugi: The ring weakens with your will.",
  "Yugi: Stay true; the path reveals itself.",
  "Yugi: Your heart is our greatest weapon.",
  "Yugi: Remember why you started.",
  "Yugi: Hope wins when you don't quit.",
  "Yugi: Every duel renews our chance.",
  "Yugi: Press on—I'm almost free!",
  "Yugi: Let your courage break chains.",
  "Yugi: Play boldly; I'll follow your lead.",
  "Yugi: Your belief fuels my escape.",
  "Yugi: Seize the moment and triumph.",
  "Yugi: I trust in your winning hand.",
  "Yugi: Rise up—cast out the Orichalcos.",
  "Yugi: Shine your light into the dark.",
  "Yugi: Hold fast; freedom is near.",
  "Yugi: Break the ring with your heart.",
  "Yugi: One last push—finish this duel.",
  "Yugi: Free us both with your courage."
];